spring.application.name=gestion

# Configuration de la base de données PostgreSQL
<<<<<<< Updated upstream
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_entreprise
spring.datasource.username=sudo_gest_entp
spring.datasource.password=gest_entp
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_entreprise_rh
spring.datasource.username=postgres
spring.datasource.password=password
>>>>>>> Stashed changes

# Configuration Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Port du serveur
server.port=8080
<<<<<<< Updated upstream
=======

#Adresse du serveur
ip.server=localhost

# Augmenter la limite de taille des fichiers
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Configuration Tomcat spécifique pour les uploads
server.tomcat.max-http-form-post-size=20MB
server.tomcat.max-swallow-size=20MB


# == CONFIGURATION EMAIL (GMAIL SMTP) ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nyainaandria.mf@gmail.com
spring.mail.password=gqwh hxhj qawp psdb 

# Properties pour Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Optional: timeout settings
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Informations sur la société
company.name=Ma Société
company.address=123 Rue Exemple
company.city=Antananarivo
company.openingtime=8
company.closingtime=17
company.workdaysperweek=5

# Paramètres du quizz
quizz.deptquestions=10
quizz.metierquestions=15
quizz.generalquestions=20
quizz.requirement=0.7

# Entretien
entretien.delay=7

>>>>>>> Stashed changes
